# Generated by Django 3.1 on 2020-08-26 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_owner', models.CharField(max_length=30)),
                ('company_name', models.CharField(max_length=30)),
                ('business_type', models.CharField(max_length=30)),
                ('contact_number', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('no_of_sites', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tank', models.CharField(max_length=120)),
                ('status', models.CharField(max_length=120)),
                ('fuelgrade', models.CharField(max_length=120)),
                ('tankfilling', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('product', models.CharField(max_length=120)),
                ('temperature', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('product_1', models.CharField(max_length=120)),
                ('water', models.CharField(max_length=120)),
                ('tc_volume', models.CharField(max_length=120)),
                ('dencity', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('mass', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rd_number', models.IntegerField()),
                ('site_name', models.CharField(max_length=30)),
                ('rd_status', models.CharField(choices=[('K-Form', 'K-Form'), ('Non K-Form', 'Non K-Form'), ('K-Form Cancellation in progress', 'K-Form Cancellation in progress'), ('K-Form Canceled', 'K-Form Canceled'), ('Others', 'Others')], default='K-Form', max_length=40)),
                ('supply_point', models.CharField(max_length=30, null=True)),
                ('dealer_name', models.CharField(max_length=30)),
                ('dealer_contact', models.CharField(max_length=30)),
                ('site_address', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=30)),
                ('tehsil', models.CharField(max_length=30)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('zone', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=30)),
                ('zone_manager', models.CharField(max_length=30)),
                ('region_manager', models.CharField(max_length=30)),
                ('dispenser', models.IntegerField()),
                ('nozzels', models.IntegerField()),
                ('atg', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='Company_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('PMG', 'PMG'), ('HSD', 'HSD'), ('HOBC', 'HOBC')], max_length=4)),
                ('area', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=20)),
                ('level', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
